### ISSUE TITLE
Factor in `get_metaflow_bucket`

### ISSUE THREAD

**Issue by jooh** [nestauk/metaflow_custom#10]
I'm factoring out generic flow code to `de_utils`. So far only one function comes up that requires metaflow - see below. Perhaps it could go to `metaflow_custom` instead? Is the plan to make `metaflow_custom` a requirement for `ojd_daps`?

https://github.com/nestauk/ojd_daps/blob/adcb1161bcf67ee1a0bbc08011258f5161f05f85/ojd_daps/flows/collect/common.py#L29-L31

https://github.com/nestauk/ojd_daps/pull/293

**Comment by bishax** [comment]
I don't know what the plan for `ojd_daps` is but future DAPS should end up depending on this repo.

I'm not sure that `get_metaflow_bucket` belongs here for a few reasons:
1. This repo is focusing on extending the internals of metaflow, whereas this function is a simple utility
2. I'm not sure I agree with the function existing (as a general utility) - a very quick search through `ojd_daps` use of the function suggests that metaflow's S3 tools can more easily be leveraged (https://docs.metaflow.org/metaflow/data#data-in-s-3-metaflow-s3)

**Comment by jooh** [comment]
Makes sense, thanks. Sounds like an `ojd_daps` refactor so I will leave this function out of `data_utils`.
